version: '3'

services:
  api:
    build: ./api
    restart: unless-stopped
    command: npm run start
    ports:
      - '3001:3000'
    environment:
      PORT: 3000

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '35000:5432'

    ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'